routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ahumadoController;
use App\Http\Controllers\chorizosController;
use App\Http\Controllers\jamonController;
use App\Http\Controllers\pacientesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/usuarios', function () {
    return view('usuarios');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/mensaje', [App\Http\Controllers\HomeController::class, 'extraer_usuarios']);

Route::resource('ahumados', ahumadoController::class);
Route::resource('chorizos', chorizosController::class);
Route::resource('jamones', jamonController::class);
Route::resource('pacientes', pacientesController::class);

app/Models/chorizos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class chorizos extends Model
{
    use HasFactory;

    protected $table = 'chorizos';
    protected $primarykey = 'id';
    public $timestamps = false;
    protected$fillable = [
        'id',
        'Nombre',
        'Peso',
        'Precio',
    ];

}

app/Http/Controllers/chorizosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\chorizos;

class chorizosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $chorizos = chorizos::all();
        return view('chorizos.index', compact('chorizos'));
       //return $chorizos;

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('chorizos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        chorizos::create($request->all());
        return redirect()->route('chorizos.index')->with('success','Producto agregado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(chorizos $chorizo)
    {
        return view('chorizos.edit',compact('chorizo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $chorizo= chorizos::find($id);
        $chorizo->update($request->all());

        return redirect()->route('chorizos.index')->with('success', 'Producto actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $chorizo= chorizos::find($id);
        $chorizo->delete();

        return redirect()->route('chorizos.index')->with('success', 'Producto eliminado');
    }
}

resources/views/chorizos/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Producto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('chorizos.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('chorizos.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Nombre del Producto:</strong>
                        <input type="text" name="Nombre" class="form-control"
                            placeholder="Ingrese el nombre del producto">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Peso del Producto:</strong>
                        <input type="text" name="Peso" class="form-control"
                            placeholder="Ingrese el peso del producto">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Precio del Producto:</strong>
                        <input type="text" name="Precio" class="form-control"
                            placeholder="Ingrese el precio del producto">
                    </div>
                </div>

                <div class="pull-right">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/chorizos/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>EDITAR REPORTE CHORIZOS</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('chorizos.index')}}">Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('chorizos.update',$chorizo->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre</strong>
                    <input type="text" name="Nombre" class="form-control" value="{{$chorizo->Nombre}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Peso</strong>
                    <input type="text" name="Peso" class="form-control" value="{{$chorizo->Peso}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Precio</strong>
                    <input type="text" name="Precio" class="form-control" value="{{$chorizo->Precio}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/chorizos/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br />
        <h4 align='center'>REPORTE DE PRODUCTOS CHORIZOS</h4>
        <div>
            <a class="btn btn-success" href="{{ route('chorizos.create')}}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{Session::get('success')}}</p>
            </div>            
        @endif
        <div class="input-group-text col-md-12">
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Peso</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
            @foreach ($chorizos as $chorizo)                
            <tr>
                <td>{{$chorizo->id}}</td>
                <td>{{$chorizo->Nombre}}</td>
                <td>{{$chorizo->Peso}}</td>
                <td>{{$chorizo->Precio}}</td>
                <td>
                        <a class="btn btn-primary" href="{{ route('chorizos.edit', $chorizo)}}">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>

                        <form action="{{ route('chorizos.destroy',$chorizo->id)}}" method="POST">
                            @csrf
                            @method('DELETE')                        
                            <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    
                </td>
            </tr>
            @endforeach
        </table>
    </div>
    </div>
@endsection