routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ahumadoController;
use App\Http\Controllers\chorizosController;
use App\Http\Controllers\jamonController;
use App\Http\Controllers\pacientesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/usuarios', function () {
    return view('usuarios');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/mensaje', [App\Http\Controllers\HomeController::class, 'extraer_usuarios']);

Route::resource('ahumados', ahumadoController::class);
Route::resource('chorizos', chorizosController::class);
Route::resource('jamones', jamonController::class);
Route::resource('pacientes', pacientesController::class);

resources/views/jamones/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Producto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('jamones.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('jamones.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Nombre del Producto:</strong>
                        <input type="text" name="Nombre" class="form-control"
                            placeholder="Ingrese el nombre del producto">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Peso del Producto:</strong>
                        <input type="text" name="Peso" class="form-control"
                            placeholder="Ingrese el peso del producto">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Precio del Producto:</strong>
                        <input type="text" name="Precio" class="form-control"
                            placeholder="Ingrese el precio del producto">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/jamones/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>EDITAR REPORTE JAMON</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('jamones.index')}}">Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('jamones.update',$jamon->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre</strong>
                    <input type="text" name="Nombre" class="form-control" value="{{$jamon->Nombre}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Peso</strong>
                    <input type="text" name="Peso" class="form-control" value="{{$jamon->Peso}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Precio</strong>
                    <input type="text" name="Precio" class="form-control" value="{{$jamon->Precio}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/jamones/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br />
        <h4 align='center'>REPORTE DE PRODUCTOS JAMON</h4>
        <div>
            <a class="btn btn-success" href="{{ route('jamones.create')}}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{Session::get('success')}}</p>
            </div>            
        @endif
        <div class="input-group-text col-md-12">
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Peso</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
            @foreach ($jamones as $jamon)                
            <tr>
                <td>{{$jamon->id}}</td>
                <td>{{$jamon->Nombre}}</td>
                <td>{{$jamon->Peso}}</td>
                <td>{{$jamon->Precio}}</td>
                <td><a class="btn btn-primary" href="{{ route('jamones.edit', $jamon)}}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>

                    <form action="{{ route('jamones.destroy',$jamon->id)}}" method="POST">
                        @csrf
                        @method('DELETE')                        
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
            </table>
        </div>
    </div>
@endsection