routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ahumadoController;
use App\Http\Controllers\chorizosController;
use App\Http\Controllers\jamonController;
use App\Http\Controllers\pacientesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/usuarios', function () {
    return view('usuarios');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/mensaje', [App\Http\Controllers\HomeController::class, 'extraer_usuarios']);

Route::resource('ahumados', ahumadoController::class);
Route::resource('chorizos', chorizosController::class);
Route::resource('jamones', jamonController::class);
Route::resource('pacientes', pacientesController::class);

app/Models/ahumado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class ahumado extends Model
{
    use HasFactory;

    protected $table = 'ahumado';
    protected $primarykey = 'id';
    public $timestamps = false;
    protected$fillable = [
        'id',
        'Nombre',
        'Peso',
        'Precio',
    ];

}

app/Http/Controllers/ahumadoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ahumado;
use Illuminate\Support\Facades\Validator;

class ahumadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
       $ahumados = ahumado::all();
       return view('ahumados.index', compact('ahumados'));
       
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ahumados.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $v = Validator::make($request->all(),[
            'Nombre'=> 'required | max:10 | unique:ahumado',
            'Peso'=> 'required | alpha_num | min:5', 
            'Precio'=> 'required | numeric', 
        ]);

        if($v->fails())
        {
            return redirect()->back()->withErrors($v->errors())->withInput();
        }else{
            ahumado::create($request->all());
            return redirect()->route('ahumados.index')->with('success','Producto agregado con exito');

        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ahumado $ahumado)
    {
        return view('ahumados.edit',compact('ahumado'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ahumado= ahumado::find($id);
        $ahumado->update($request->all());

        return redirect()->route('ahumados.index')->with('success', 'Producto actualizado');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id 
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ahumado= ahumado::find($id);
        $ahumado->delete();

        return redirect()->route('ahumados.index')->with('success', 'Producto eliminado');        
    }
}

resources/views/ahumados/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Producto</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('ahumados.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('ahumados.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Nombre del Producto:</strong>
                        <input type="text" name="Nombre" class="form-control"
                            placeholder="Ingrese el nombre del producto" required>                        
                        @error('Nombre')
                            <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Peso del Producto:</strong>
                        <input type="text" name="Peso" class="form-control"
                            placeholder="Ingrese el peso del producto" required>
                        @error('Peso')
                            <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Precio del Producto:</strong>
                        <input type="text" name="Precio" class="form-control"
                            placeholder="Ingrese el precio del producto" required>
                        @error('Precio')
                            <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Observaciones:</strong>
                        <input type="text" name="Precio" class="form-control"
                            placeholder="Ingrese el precio del producto" maxlength="5" required>
                        @error('Precio')
                            <p>{{$message}}</p>
                        @enderror
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Telefono validacion:</strong>
                        <input type="text" name="telefono" class="form-control"
                            placeholder="Ingrese el precio del producto" required pattern="[+][0-5]{3} [0-9]{9}">
                        
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/ahumados/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>EDITAR REPORTE ahumado</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('ahumados.index')}}">Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('ahumados.update',$ahumado->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre</strong>
                    <input type="text" name="Nombre" class="form-control" value="{{$ahumado->Nombre}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Peso</strong>
                    <input type="text" name="Peso" class="form-control" value="{{$ahumado->Peso}}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Precio</strong>
                    <input type="text" name="Precio" class="form-control" value="{{$ahumado->Precio}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/ahumados/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <br />
        <h4 align='center'>REPORTE DE PRODUCTOS AHUMADOS</h4>
        <div>
            <a class="btn btn-success" href="{{ route('ahumados.create')}}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{Session::get('success')}}</p>
            </div>            
        @endif
        <div class="input-group-text col-md-12">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Peso</th>
                    <th>Precio</th>
                    <th>Acciones</th>
                </tr>
                @foreach ($ahumados as $ahumado)                
                <tr>
                    <td>{{$ahumado->id}}</td>
                    <td>{{$ahumado->Nombre}}</td>
                    <td>{{$ahumado->Peso}}</td>
                    <td>{{$ahumado->Precio}}</td>
                    <td>    <a class="btn btn-primary" href="{{ route('ahumados.edit', $ahumado)}}">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                        
                            <form action="{{ route('ahumados.destroy',$ahumado->id)}}" method="POST">
                                @csrf
                                @method('DELETE')                        
                                <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection